<html><head></head><body><div class="chapter" title="Chapter&#xA0;2.&#xA0;Dealing with Exceptions"><div class="titlepage"><div><div><h1 class="title"><a id="ch02"/>Chapter 2. Dealing with Exceptions</h1></div></div></div><p>In the previous chapter, we started with a simple command-line script and gradually transformed it into an object-oriented code. Several new features were added in the process. So far, we have paid little attention to the application quality. We neglected to look for any obvious errors encountered during the program execution. Such errors detected during the application runtime are referred to as<a id="id91" class="indexterm"/> <span class="strong"><strong>exceptions</strong></span>. In this chapter, you will learn techniques to make the application more robust by handling exceptions.</p><p>Specifically, we will cover the following topics:</p><div class="itemizedlist"><ul class="itemizedlist"><li class="listitem" style="list-style-type: disc">What are the exceptions in Python?</li><li class="listitem" style="list-style-type: disc">Controlling the program flow with the <code class="literal">try…except</code> clause</li><li class="listitem" style="list-style-type: disc">Dealing with common problems by handling exceptions</li><li class="listitem" style="list-style-type: disc">Creating and using custom exception classes</li></ul></div><p>Let's start by reviewing the feedback you received from the users.</p><div class="section" title="Revisiting Attack of the Orcs v1.0.0"><div class="titlepage"><div><div><h1 class="title"><a id="ch02lvl1sec17"/>Revisiting Attack of the Orcs v1.0.0</h1></div></div></div><p>The <a id="id92" class="indexterm"/>heal feature added in v1.0.0 became a hit among the core users. The OOP approach put you in a better position to implement new features (or so you thought!). As the feature requests started pouring in, so did the reported bugs.</p><div class="informaltable"><table border="1"><colgroup><col style="text-align: left"/></colgroup><tbody><tr><td style="text-align: left" valign="top">
<p>
<span class="emphasis"><em>The game is OK, but there are several annoyances. For example, when prompted to choose a hut, sometimes I input a number greater than 5 or input a character by mistake. After this, it just prints some weird error message and the application terminates. Can you fix this?</em></span>
</p>
</td></tr></tbody></table></div><div class="mediaobject"><img src="graphics/B05034_02_01.jpg" alt="Revisiting Attack of the Orcs v1.0.0"/></div><div class="section" title="Debugging the problem"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec28"/>Debugging the problem</h2></div></div></div><p>Let's try to <a id="id93" class="indexterm"/>reproduce the reported problem. Run the example from <a class="link" href="ch01.html" title="Chapter 1. Developing Simple Applications">Chapter 1</a>, <span class="emphasis"><em>Developing Simple Applications</em></span>:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>$ python ch01_ex03.py</strong></span>
</pre></div><p>When prompted for the hut number, enter any character, as shown in the following screenshot:</p><div class="mediaobject"><img src="graphics/B05034_02_02.jpg" alt="Debugging the problem"/></div><p>The application<a id="id94" class="indexterm"/> is terminated with an error <span class="strong"><strong>traceback</strong></span>
<a id="id95" class="indexterm"/> in the console. A traceback is a snapshot of the call stack at the point where the exception (the error) occurred. In this particular example, the <code class="literal">_process_user_choice</code> method is called by the <code class="literal">play</code> method, which is called directly from the module. The line numbers show where these calls occur. It is useful for debugging. The reported error in this case is <code class="literal">ValueError</code>. It occurred because we assumed the user choice as an integer. The other problem reported is when the hut number does not fall in the range 1 to 5. The traceback error received is <code class="literal">IndexError</code>. It occurs while accessing the entry in the <code class="literal">huts</code> list corresponding to the user input:</p><div class="mediaobject"><img src="graphics/B05034_02_03.jpg" alt="Debugging the problem"/></div><p>If you look at the two tracebacks closely, both these errors occur in the <code class="literal">_process_user_choice</code> method of the <code class="literal">AttackOfTheOrcs</code> class. Let's review the original method:</p><div class="mediaobject"><img src="graphics/B05034_02_04.jpg" alt="Debugging the problem"/></div><p>Good! We have<a id="id96" class="indexterm"/> pinpointed where the problem is. Now, the next task is to fix these bugs.</p></div><div class="section" title="Fixing the bugs…"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec29"/>Fixing the bugs…</h2></div></div></div><div class="informaltable"><table border="1"><colgroup><col style="text-align: left"/></colgroup><tbody><tr><td style="text-align: left" valign="top">
<p>
<span class="emphasis"><em>Sir Foo has some thoughts on fixing bugs…</em></span>
</p>
</td></tr></tbody></table></div><div class="mediaobject"><img src="graphics/B05034_02_05.jpg" alt="Fixing the bugs…"/></div><div class="informaltable"><table border="1"><colgroup><col style="text-align: left"/></colgroup><tbody><tr><td style="text-align: left" valign="top">
<p>
<span class="emphasis"><em>Sure. One way to fix the reported problems is to add conditional blocks which ensure that the user input is a number between 1 and 5.</em></span>
</p>
</td></tr></tbody></table></div><p>But like many <a id="id97" class="indexterm"/>other languages, Python provides an elegant way to handle such situations using the <code class="literal">try…except</code> clause. It is based on the <span class="strong"><strong>Easier to Ask for Forgiveness than Permission</strong></span> (<span class="strong"><strong>EAFP</strong></span>) principle<a id="id98" class="indexterm"/>.</p><div class="note" title="Note" style=""><div class="inner"><h3 class="title"><a id="note03"/>Note</h3><p>
<span class="strong"><strong>The EAFP principle</strong></span>
</p><p>When coding, you assume some things exist and try writing the code accordingly. But if this turns out to be a wrong assumption, you ask for forgiveness by catching that exception. This is a very common approach used in Python development. You can check out the Python 3 documentation (<a class="ulink" href="https://docs.python.org/3/glossary.html">https://docs.python.org/3/glossary.html</a>) that defines this idiom. In some cases, exception handling can affect the performance when compared to the use of the <code class="literal">if</code> condition blocks; however, you will most likely find more good things than bad ones when using the <code class="literal">try…except</code> clause.</p></div></div></div></div></div>
<div class="section" title="Exceptions"><div class="titlepage"><div><div><h1 class="title"><a id="ch02lvl1sec18"/>Exceptions</h1></div></div></div><p>Before <a id="id99" class="indexterm"/>jumping straight into the code and fixing these issues, let's first understand what an exception is and what we mean by handling an exception.</p><div class="section" title="What is an exception?"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec30"/>What is an exception?</h2></div></div></div><p>An <span class="strong"><strong>exception</strong></span> is an object in Python. It gives us information about an error detected during the program execution. The errors noticed while debugging the application were <span class="strong"><strong>unhandled exceptions</strong></span>
<a id="id100" class="indexterm"/> as we didn't see those coming. Later in the chapter, you will learn the techniques to handle these exceptions.</p><p>The <code class="literal">ValueError</code> and <code class="literal">IndexError</code> exceptions seen in the earlier tracebacks are examples of built-in exception types in Python. In the following section, you will learn about some other built-in exceptions supported in Python.</p></div><div class="section" title="Most common exceptions"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec31"/>Most common exceptions</h2></div></div></div><p>Let's quickly review some of the most frequently encountered exceptions. The easiest way is to try running some buggy code and let it report the problem as an error traceback! Start your Python interpreter and write the following code:</p><div class="mediaobject"><img src="graphics/B05034_02_06.jpg" alt="Most common exceptions"/></div><p>Here are a few more exceptions:</p><div class="mediaobject"><img src="graphics/B05034_02_07.jpg" alt="Most common exceptions"/></div><p>As you can see, each <a id="id101" class="indexterm"/>line of the code throws an error traceback with an exception type (shown highlighted). These are a few of the built-in exceptions in Python. A comprehensive list of built-in exceptions<a id="id102" class="indexterm"/> can be found at <a class="ulink" href="https://docs.python.org/3/library/exceptions.html#bltin-exceptions">https://docs.python.org/3/library/exceptions.html#bltin-exceptions</a>.</p><p>Python provides <code class="literal">BaseException</code> as the base class for all built-in exceptions. However, most of the built-in exceptions do not directly inherit <code class="literal">BaseException</code>. Instead, they are derived from a class called <code class="literal">Exception</code> that in turn inherits from <code class="literal">BaseException</code>. The built-in exceptions that deal with program exit (for example, <code class="literal">SystemExit</code>) are derived directly from <code class="literal">BaseException</code>. You can also create your own exception class as a subclass of <code class="literal">Exception</code>. You will learn about that later in this chapter.</p></div><div class="section" title="Exception handling"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec32"/>Exception handling</h2></div></div></div><p>So far, we saw have seen the<a id="id103" class="indexterm"/> exceptions occur. Now it is time to learn how to use the <code class="literal">try…except</code> clause to handle these exceptions. The following pseudocode shows a very simple example of the <code class="literal">try…except</code> clause:</p><div class="mediaobject"><img src="graphics/B05034_02_08.jpg" alt="Exception handling"/></div><p>Let's review the preceding code snippet:</p><div class="itemizedlist"><ul class="itemizedlist"><li class="listitem" style="list-style-type: disc">First, the program tries to execute the code inside the <code class="literal">try</code> clause.</li><li class="listitem" style="list-style-type: disc">During this execution, if something goes wrong (if an exception occurs), it jumps out of this <code class="literal">try</code> clause. The remaining code in the <code class="literal">try</code> block is not executed.</li><li class="listitem" style="list-style-type: disc">It then looks for an appropriate exception handler in the <code class="literal">except</code> clause and executes it.</li></ul></div><p>The <code class="literal">except</code> clause <a id="id104" class="indexterm"/>used here is a universal one. It will catch all types of exceptions occurring within the <code class="literal">try</code> clause. Instead of having this "catch-all" handler, a better practice is to catch the errors that you anticipate and write an exception handling code specific to those errors. For example, the code in the <code class="literal">try</code> clause might throw an <code class="literal">AssertionError</code>. Instead of using the universal <code class="literal">except</code> clause, you can write a specific exception handler, as follows:</p><div class="mediaobject"><img src="graphics/B05034_02_09.jpg" alt="Exception handling"/></div><p>Here, we have an <code class="literal">except</code> clause that exclusively deals with <code class="literal">AssertionError</code>. What it also means is that any error other than the <code class="literal">AssertionError</code> will slip through as an unhandled exception. For that, we need to define multiple <code class="literal">except</code> clauses with different exception handlers. However, at any point in time, only one exception handler will be called. This can be better explained with an example. Let's take a look at the following code snippet:</p><div class="mediaobject"><img src="graphics/B05034_02_10.jpg" alt="Exception handling"/></div><p>The <code class="literal">try</code> block calls <code class="literal">solve_something()</code>. This function accepts a number as a user input and makes an assertion that the number is greater than zero. If the assertion fails, it jumps directly to the handler, <code class="literal">except AssertionError</code>.</p><p>In the other <a id="id105" class="indexterm"/>scenario, with <code class="literal">a &gt; 0</code>, the rest of the code in <code class="literal">solve_something()</code> is executed. You will notice that the variable <code class="literal">x</code> is not defined, which results in <code class="literal">NameError</code>. This exception is handled by the other exception clause, <code class="literal">except NameError</code>. Likewise, you can define specific exception handlers for anticipated errors.</p></div><div class="section" title="Raising and re-raising an exception"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec33"/>Raising and re-raising an exception</h2></div></div></div><p>The <code class="literal">raise</code> keyword <a id="id106" class="indexterm"/>in Python is used to force an exception to occur. Put <a id="id107" class="indexterm"/>another way, it <a id="id108" class="indexterm"/>raises an exception. The syntax is simple; just open the Python interpreter and type:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>&gt;&gt;&gt; raise AssertionError("some error message")</strong></span>
</pre></div><p>This produces the following error traceback:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>Traceback (most recent call last): </strong></span>
<span class="strong"><strong>  File "&lt;stdin&gt;", line 1, in &lt;module&gt; </strong></span>
<span class="strong"><strong>AssertionError :  some error message</strong></span>
</pre></div><p>In some situations, we need to re-raise an exception. To understand this concept better, here is a trivial scenario. Suppose, in the <code class="literal">try</code> clause, you have an expression that divides a number by zero. In ordinary arithmetic, this expression has no meaning. It's a bug! This causes the program to raise an exception called <code class="literal">ZeroDivisionError</code>. If there is no exception handling code, the program will just print the error message and terminate.</p><p>What if you wish to <a id="id109" class="indexterm"/>write this error to some log file and then terminate the program? Here, you<a id="id110" class="indexterm"/> can use an <code class="literal">except</code> clause to log the error first. Then, use the <code class="literal">raise</code> keyword without any arguments to re-raise the exception. The exception will be propagated upwards in the stack. In this example, it terminates the program. The exception can be re-raised with the <code class="literal">raise</code> keyword without any arguments.</p><p>Here is an example that shows how to re-raise an exception:</p><div class="mediaobject"><img src="graphics/B05034_02_11.jpg" alt="Raising and re-raising an exception"/></div><p>As can be seen, a division by zero exception is raised while solving the <code class="literal">a/b</code> expression. This is because the value of variable <code class="literal">b</code> is set to <code class="literal">0</code>. For illustration purposes, we assumed that there is no specific exception handler for this error. So, we will use the general <code class="literal">except</code> clause where the exception is re-raised after logging the error. If you want to try this yourself, just write the code illustrated earlier in a new Python file, and run it from a terminal window. The <a id="id111" class="indexterm"/>following <a id="id112" class="indexterm"/>screenshot shows the output of the preceding code:</p><div class="mediaobject"><img src="graphics/B05034_02_12.jpg" alt="Raising and re-raising an exception"/></div></div><div class="section" title="The else block of try…except"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec34"/>The else block of try…except</h2></div></div></div><p>There<a id="id113" class="indexterm"/> is an optional <code class="literal">else</code> block that can be specified in the <code class="literal">try…except</code> clause. The <code class="literal">else</code> block is <a id="id114" class="indexterm"/>executed only if no exception occurs in the <code class="literal">try…except</code> clause. The syntax is as follows:</p><div class="mediaobject"><img src="graphics/B05034_02_13.jpg" alt="The else block of try…except"/></div><p>The <code class="literal">else</code> block is executed before the <code class="literal">finally</code> clause, which we will study next.</p></div><div class="section" title="finally...clean it up!"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec35"/>finally...clean it up!</h2></div></div></div><p>There is something else to add to<a id="id115" class="indexterm"/> the <code class="literal">try…except…else</code> story: an <a id="id116" class="indexterm"/>optional <code class="literal">finally</code> clause. As the name suggests, the code within this clause is executed at the end of the associated <code class="literal">try…except</code> block. Whether or not an exception is raised, the <code class="literal">finally</code> clause, if specified, will certainly get executed at the end of the <code class="literal">try…except</code> clause. Imagine it as an all-weather guarantee given by Python! The following code snippet shows the <code class="literal">finally</code> block in action:</p><div class="mediaobject"><img src="graphics/B05034_02_14.jpg" alt="finally...clean it up!"/></div><p>Running this simple <a id="id117" class="indexterm"/>code will<a id="id118" class="indexterm"/> produce the following output:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>$ python finally_example1.py </strong></span>
<span class="strong"><strong>Enter a number: -1</strong></span>
<span class="strong"><strong>Uh oh..Assertion Error. </strong></span>
<span class="strong"><strong>Do some special cleanup </strong></span>
</pre></div><p>The last line in the output is the <code class="literal">print</code> statement from the <code class="literal">finally</code> clause.</p><div class="mediaobject"><img src="graphics/B05034_02_15.jpg" alt="finally...clean it up!"/></div><div class="informaltable"><table border="1"><colgroup><col style="text-align: left"/></colgroup><tbody><tr><td style="text-align: left" valign="top">
<p>
<span class="emphasis"><em>That's a good question! Let's add a twist to the tale. What if the new code in the except clause forces a return from the function? In such a scenario, will your solution execute the last line of code shown in the earlier screenshot?</em></span>
</p>
</td></tr></tbody></table></div><p>The code snippets <a id="id119" class="indexterm"/>with and <a id="id120" class="indexterm"/>without the <code class="literal">finally</code> clause are shown in the following screenshot. The code in the <code class="literal">finally</code> clause is assured to be executed in the end, even when the <code class="literal">except</code> clause instructs the code to return from the function.</p><div class="mediaobject"><img src="graphics/B05034_02_16.jpg" alt="finally...clean it up!"/></div><p>The <code class="literal">finally</code> clause <a id="id121" class="indexterm"/>is typically <a id="id122" class="indexterm"/>used to perform clean-up tasks before leaving the function. An example use case is to close a database connection or a file. However, note that, for this purpose, you can also use the <code class="literal">with</code> statement in Python.</p></div></div>
<div class="section" title="Back to the game &#x2013; Attack of the Orcs v1.1.0"><div class="titlepage"><div><div><h1 class="title"><a id="ch02lvl1sec19"/>Back to the game – Attack of the Orcs v1.1.0</h1></div></div></div><p>With this knowledge of the<a id="id123" class="indexterm"/> exception handling, let's work on the next incremental version of the application.</p><div class="section" title="Preparatory work"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec36"/>Preparatory work</h2></div></div></div><p>Before <a id="id124" class="indexterm"/>writing any code, let's first understand how the rest of the section is organized. In a nutshell, we will start with v1.0.0 of the code from <a class="link" href="ch01.html" title="Chapter 1. Developing Simple Applications">Chapter 1</a>, <span class="emphasis"><em>Developing Simple Applications,</em></span> progressively add the exception handling code, and call the new version v1.1.0.</p><div class="note" title="Note" style=""><div class="inner"><h3 class="title"><a id="note04"/>Note</h3><p>The Python files in the supporting code bundle already include the exception handling code to be discussed in this section as well as in a later section of this chapter, <span class="emphasis"><em>Defining custom exceptions</em></span>
</p></div></div><p>The following points elaborate further details:</p><div class="itemizedlist"><ul class="itemizedlist"><li class="listitem" style="list-style-type: disc">We will start by downloading the v1.0.0 of the game from <a class="link" href="ch01.html" title="Chapter 1. Developing Simple Applications">Chapter 1</a>, <span class="emphasis"><em>Developing Simple Applications</em></span>. The file name is <code class="literal">ch01_ex03_AbstractBaseClass.py</code> (recall that this was provided as a solution to an exercise in <a class="link" href="ch01.html" title="Chapter 1. Developing Simple Applications">Chapter 1</a>, <span class="emphasis"><em>Developing Simple Applications</em></span>). You can find this file in this chapter's code bundle.</li><li class="listitem" style="list-style-type: disc">Compare the aforementioned file with <code class="literal">ch01_ex03.py</code>. The only difference here is the use of an abstract base class, <code class="literal">AbstractGameUnit</code>, instead of an ordinary base class, <code class="literal">GameUnit</code>. The rest of the code is identical.</li><li class="listitem" style="list-style-type: disc">Let's copy <code class="literal">ch01_ex03_AbstractBaseClass.py</code> and save it as <code class="literal">attackoftheorcs_v1_1.py</code>. or give it any name you like. In the following discussion, we will refer to the file by this new name and incrementally add exception handling code to it.</li><li class="listitem" style="list-style-type: disc">As noted before, the supporting code bundle has all the exception handling code that we will review. You will find a file by the same name (<code class="literal">attackoftheorcs_v1_1.py</code>) in the code bundle with all the changes included.</li></ul></div></div><div class="section" title="Adding the exception handling code"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec37"/>Adding the exception handling code</h2></div></div></div><p>This will <a id="id125" class="indexterm"/>essentially be a bug-fix version with no new features added. The debugging done earlier has already helped us find where the problems are. Open the Python file (<code class="literal">attackoftheorcs_v1_1.py</code>) and update the <code class="literal">_process_user_choice</code> method of the <code class="literal">AbstractGameUnit</code> class. The updated version of this method with the new <code class="literal">try…except</code> clauses is shown in the following code snippet:</p><div class="mediaobject"><img src="graphics/B05034_02_17.jpg" alt="Adding the exception handling code"/></div><div class="note" title="Note" style=""><div class="inner"><h3 class="title"><a id="tip17"/>Tip</h3><p>In case you missed reading this earlier, you should copy the <code class="literal">ch01_ex03_AbstractBaseClass.py</code> file and name it <code class="literal">attackoftheorcs_v1_1.py</code>. Then work with this new file to add the preceding exception handling code. Alternatively, you can simply review the file with the same name provided in the code bundle for this chapter. It includes all the changes we will discuss next. The Python 2.7.9 compatible source file is also provided in the code bundle.</p></div></div><p>Let's review the<a id="id126" class="indexterm"/> preceding code:</p><div class="itemizedlist"><ul class="itemizedlist"><li class="listitem" style="list-style-type: disc">In the <code class="literal">try</code> clause, if the <code class="literal">user_choice</code> variable is not a number, the <code class="literal">ValueError</code> exception occurs, which is handled by <code class="literal">except ValueError as e</code></li><li class="listitem" style="list-style-type: disc">The <code class="literal">as</code> keyword is used to assign exception to an <code class="literal">e</code> object</li><li class="listitem" style="list-style-type: disc">Alternatively, you can just use the syntax <code class="literal">except ValueError</code></li><li class="listitem" style="list-style-type: disc">The second <code class="literal">try…except</code> clause takes care of the situation where the input number goes out of range of the <code class="literal">huts</code> list</li><li class="listitem" style="list-style-type: disc">When the <code class="literal">IndexError</code> exception occurs, the <code class="literal">continue</code> statement in the <code class="literal">except</code> clause makes the user re-enter the input</li></ul></div><p>That's all we need. Now, let's <a id="id127" class="indexterm"/>run the application next.</p></div><div class="section" title="Running Attack of the Orcs v1.1.0"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec38"/>Running Attack of the Orcs v1.1.0</h2></div></div></div><p>It is time to run the application<a id="id128" class="indexterm"/> and see if these changes fix the reported problems. Run the program in a terminal window, as shown in the following code snippet:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>$ python attackoftheorcs_v1_1.py</strong></span>
</pre></div><p>When prompted for an input, enter some unacceptable value for the hut number:</p><div class="mediaobject"><img src="graphics/B05034_02_18.jpg" alt="Running Attack of the Orcs v1.1.0"/></div><p>Looks good! At least the reported problems have been resolved. It is easy to find more such errors. For example, a user can still enter 0 or a negative number while choosing a hut, or, when the program asks for permission to attack the enemy, any input other than <code class="literal">y</code> or <code class="literal">n</code> is not handled gracefully. As an exercise, have a go at fixing these issues yourself!</p></div></div>
<div class="section" title="Defining custom exceptions"><div class="titlepage"><div><div><h1 class="title"><a id="ch02lvl1sec20"/>Defining custom exceptions</h1></div></div></div><p>You can<a id="id129" class="indexterm"/> define your own exception class by inheriting from the <code class="literal">Exception</code> base class or any other exception class. Why do we need such customization? Firstly, you can create an exception class with a descriptive name. This allows us to identify the purpose of the exception just by looking at the descriptive name. For example, instead of <code class="literal">ValueError</code>, a custom exception named <code class="literal">ValueGreaterThanFiveError</code> will immediately help identify the problem. There are other advantages as well. You can use such classes to add customized messages based on error subcategories, writing<a id="id130" class="indexterm"/> error logs, and so on. Let's learn how to define custom exceptions next.</p><div class="section" title="Preparatory work"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec39"/>Preparatory work</h2></div></div></div><p>Here is a list of files we will use:</p><div class="itemizedlist"><ul class="itemizedlist"><li class="listitem" style="list-style-type: disc"><code class="literal">attackoftheorcs_v1_1.py</code>: This is the file from the previous section that we will use. As mentioned earlier, the supporting code bundle already has a file by the same name. It includes all the modifications we will discuss.</li><li class="listitem" style="list-style-type: disc"><code class="literal">gameuniterror.py</code>: This is a new module to hold a custom exception class.</li><li class="listitem" style="list-style-type: disc"><code class="literal">heal_exception_example.py</code>: This is where the top-level control code will be written. This is a<a id="id131" class="indexterm"/> simplified version of the game where we do not need to play the whole game in order to reproduce the problem.</li></ul></div><p>You need to put all the aforementioned files in the same directory.</p></div><div class="section" title="Custom exception – The problem"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec40"/>Custom exception – The problem</h2></div></div></div><p>To demonstrate the use of<a id="id132" class="indexterm"/> custom exceptions, let's identify a trivial problem. Observe the <code class="literal">heal</code> method shown next (recall that it is defined in <code class="literal">AbstractGameUnit</code>, the superclass of <code class="literal">Knight</code>). You can find it in the <code class="literal">attackoftheorcs_v1_1.py</code> file.</p><div class="mediaobject"><img src="graphics/B05034_02_19.jpg" alt="Custom exception – The problem"/></div><p>The method has two optional arguments. If <code class="literal">full_healing</code> is set to <code class="literal">True</code>, the game unit will regain all its lost hit points. The other option, <code class="literal">heal_by</code>, heals the game unit by a small amount. In this version, we are not using the <code class="literal">heal_by</code> option. But in a future version, you may want to introduce a turn-based feature in the game, where the injured units are healed by a small amount on every turn<span class="emphasis"><em>.</em></span>
</p><p>To demonstrate how to create and use custom exceptions, let's introduce an artificial bug in the <code class="literal">heal_by</code> feature! Save the following code as <code class="literal">heal_exception_example.py</code> and place this file in the same directory as<code class="literal"> attackoftheorcs_v1_1.py</code>.</p><div class="mediaobject"><img src="graphics/B05034_02_20.jpg" alt="Custom exception – The problem"/></div><p>This is a simplified<a id="id133" class="indexterm"/> version of the game where we do not need to play the whole game in order to create this artificial bug! It is a top-level control code that creates a <code class="literal">Knight</code> instance, forcefully reduces the hit points (check out <code class="literal">knight.health_meter</code>) as if the knight has fought a combat and sustained injuries. In the end, it calls the <code class="literal">heal</code> function with the <code class="literal">heal_by</code> argument.</p><p>Have you noticed a problem here? Recall that the <code class="literal">knight</code> instance can have a maximum of <code class="literal">40</code> hit points (check out the instance attribute <code class="literal">Knight.max_hp</code>). The preceding code is trying to <code class="literal">heal</code> the knight by <code class="literal">100</code> points using the <code class="literal">heal_by</code> argument. Clearly, it will exceed the limit. One way of preventing this is to add an assertion statement in the <code class="literal">heal</code> method, as shown in the following code snippet:</p><div class="informalexample"><pre class="programlisting">assert (self.health_meter + heal_by  &lt;= self.max_hp)</pre></div><p>This will raise an <code class="literal">AssertionError</code>. This is an acceptable solution. Another way to accomplish this is to use a custom exception class. It is demonstrated next.</p></div><div class="section" title="Writing a new exception class"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec41"/>Writing a new exception class</h2></div></div></div><p>It is trivial to create a <a id="id134" class="indexterm"/>new exception class derived from <code class="literal">Exception</code>. Open your Python interpreter and create the following class:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>&gt;&gt;&gt; class GameUnitError(Exception):</strong></span>
<span class="strong"><strong>...     pass</strong></span>
<span class="strong"><strong>... </strong></span>
<span class="strong"><strong>&gt;&gt;&gt;</strong></span>
</pre></div><p>That's all! We have a new exception class, <code class="literal">GameUnitError</code>, ready to be deployed. How to test this exception? Just <code class="literal">raise</code> it. Type the following line of code in your Python interpreter:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>&gt;&gt;&gt; raise GameUnitError("ERROR: some problem with game unit")</strong></span>
</pre></div><p>Raising the newly created exception will print the following traceback:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>&gt;&gt;&gt; raise GameUnitError("ERROR: some problem with game unit")</strong></span>
<span class="strong"><strong>Traceback (most recent call last):</strong></span>
<span class="strong"><strong>  File "&lt;stdin&gt;", line 1, in &lt;module&gt;</strong></span>
<span class="strong"><strong>__main__.GameUnitError: ERROR: some problem with game unit</strong></span>
</pre></div><p>Copy the<a id="id135" class="indexterm"/> <code class="literal">GameUnitError</code> class into its own module, <code class="literal">gameuniterror.py</code>, and save it in the same directory as <code class="literal">attackoftheorcs_v1_1.py</code>.</p><p>Next, update the <code class="literal">attackoftheorcs_v1_1.py</code> file to include the following changes:</p><div class="itemizedlist"><ul class="itemizedlist"><li class="listitem" style="list-style-type: disc">First, add the following import statement at the beginning of the file:<div class="informalexample"><pre class="programlisting">from gameuniterror import GameUnitError</pre></div></li><li class="listitem" style="list-style-type: disc">The second change is in the <code class="literal">AbstractGameUnit.heal</code> method. The updated code is shown in the following code snippet. Observe the highlighted code that raises the custom exception whenever the value of <code class="literal">self.health_meter</code> exceeds that of <code class="literal">self.max_hp</code>.<div class="mediaobject"><img src="graphics/B05034_02_21.jpg" alt="Writing a new exception class"/></div></li></ul></div><p>With these two changes, run <code class="literal">heal_exception_example.py</code> created earlier. You will see the new exception being raised, as shown in the following screenshot:</p><div class="mediaobject"><img src="graphics/B05034_02_22.jpg" alt="Writing a new exception class"/></div></div><div class="section" title="Expanding the exception class"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec42"/>Expanding the exception class</h2></div></div></div><p>Can we do <a id="id136" class="indexterm"/>something more with the <code class="literal">GameUnitError</code> class? Certainly! Just like any other class, we can define attributes and use them. Let's expand this class further. In the modified version, it will accept an additional argument and some predefined error code. The updated <code class="literal">GameUnitError</code> class is shown in the following screenshot:</p><div class="mediaobject"><img src="graphics/B05034_02_23.jpg" alt="Expanding the exception class"/></div><p>Let's take a look at the code in the preceding screenshot:</p><div class="itemizedlist"><ul class="itemizedlist"><li class="listitem" style="list-style-type: disc">First, it calls the <code class="literal">__init__</code> method of the <code class="literal">Exception</code> superclass and then defines some additional instance variables.</li><li class="listitem" style="list-style-type: disc">A new dictionary object, <code class="literal">self.error_dict</code>, holds the error integer code and the error information as key-value pairs.</li><li class="listitem" style="list-style-type: disc">The <code class="literal">self.error_message</code> stores the information about the current error depending on the error code provided.</li><li class="listitem" style="list-style-type: disc">The <code class="literal">try…except</code> clause ensures that <code class="literal">error_dict</code> actually has the key specified by the <code class="literal">code</code> argument. It doesn't in the <code class="literal">except</code> clause; we just retrieve the value with the default error code of <code class="literal">000</code>.</li></ul></div><p>Now, let's take<a id="id137" class="indexterm"/> look at the consumer of this class. Observe the modified <code class="literal">heal</code> method. The only change here is the additional argument to the <code class="literal">GameUnitError</code> instance. Here, we pass an error code as the second argument:</p><div class="mediaobject"><img src="graphics/B05034_02_24.jpg" alt="Expanding the exception class"/></div><p>So far, we have made changes to the <code class="literal">GameUnitError</code> class and the <code class="literal">AbstractGameUnit.heal</code> method. We are not done yet. The last piece of the puzzle is to modify the <code class="literal">main</code> program in the <code class="literal">heal_exception_example.py</code> file. The code is shown in the following screenshot:</p><div class="mediaobject"><img src="graphics/B05034_02_25.jpg" alt="Expanding the exception class"/></div><p>Let's review <a id="id138" class="indexterm"/>the code:</p><div class="itemizedlist"><ul class="itemizedlist"><li class="listitem" style="list-style-type: disc">As the <code class="literal">heal_by</code> value is too large, the <code class="literal">heal</code> method in the <code class="literal">try</code> clause raises the <code class="literal">GameUnitError</code> exception.</li><li class="listitem" style="list-style-type: disc">The new <code class="literal">except</code> clause handles the <code class="literal">GameUnitError</code> exception just like any other built-in exceptions.</li><li class="listitem" style="list-style-type: disc">Within the <code class="literal">except</code> clause, we have two <code class="literal">print</code> statements. The first one prints <code class="literal">health_meter &gt; max_hp!</code> (recall that, when this exception was raised in the <code class="literal">heal</code> method, this string was given as the first argument to the <code class="literal">GameUnitError</code> instance). The second <code class="literal">print</code> statement retrieves and prints the <code class="literal">error_message</code> attribute of the <code class="literal">GameUnitError</code> instance.</li></ul></div><p>We have got all the changes in place. We can run this example from a terminal window as:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>$ python heal_exception_example.py</strong></span>
</pre></div><p>The output of the program is shown in the following screenshot:</p><div class="mediaobject"><img src="graphics/B05034_02_26.jpg" alt="Expanding the exception class"/></div><p>In this simple <a id="id139" class="indexterm"/>example, we have just printed the error information to the console. You can further write verbose error logs to a file and keep track of all the error messages generated while the application is running.</p></div><div class="section" title="Inheriting from the exception class"><div class="titlepage"><div><div><h2 class="title"><a id="ch02lvl2sec43"/>Inheriting from the exception class</h2></div></div></div><div class="informaltable"><table border="1"><colgroup><col style="text-align: left"/></colgroup><tbody><tr><td style="text-align: left" valign="top">
<p>
<span class="emphasis"><em>Sir Foo has </em></span>
<a id="id140" class="indexterm"/>
<span class="emphasis"><em>something to say about the error codes maintained in </em></span>
<code class="literal">GameUnitError.error_dict</code><span class="emphasis"><em> seen earlier…</em></span>
</p>
</td></tr></tbody></table></div><div class="mediaobject"><img src="graphics/B05034_02_28.jpg" alt="Inheriting from the exception class"/></div><div class="informaltable"><table border="1"><colgroup><col style="text-align: left"/></colgroup><tbody><tr><td style="text-align: left" valign="top">
<p>
<span class="emphasis"><em>You are right. While raising an exception, you need to remember what each error number corresponds to. Let's discuss a few alternatives.</em></span>
</p>
</td></tr></tbody></table></div><p>One option is to<a id="id141" class="indexterm"/> use unique strings as keys of <code class="literal">error_dict</code> in place of the error numbers, for example:</p><div class="informalexample"><pre class="programlisting">self.error_dict = { 
    'health_meter_problem':"ERROR: Health meter problem!"}</pre></div><p>This alleviates the problem of remembering the error codes. However, this approach is not suitable if you want to do something beyond just printing a message. For example, depending on the error type, you may want to do some additional processing.</p><p>A better approach is to use <code class="literal">GameUnitError</code> as a base exception class and derive new classes that target specific errors. The descriptive names of these exception classes should help convey the same information. The following code snippet shows an example of how to do it. You can replace the existing code in <code class="literal">gameuniterror.py</code> with the one shown in the following screenshot:</p><div class="mediaobject"><img src="graphics/B05034_02_29.jpg" alt="Inheriting from the exception class"/></div><p>Now, in the <code class="literal">heal</code> <a id="id142" class="indexterm"/>method, instead of raising the <code class="literal">GameUnitError</code> exception, just <code class="literal">raise</code> the <code class="literal">HealthMeterException</code>. Be sure to <code class="literal">import</code> the <code class="literal">HealthMeterException</code> module as indicated in the following code snippet:</p><div class="mediaobject"><img src="graphics/B05034_02_30.jpg" alt="Inheriting from the exception class"/></div><p>Running the code with the aforementioned changes produces a similar output. It is just that we have revised <code class="literal">error_message</code> of the <code class="literal">HealthMeterException</code> class. The output is shown as follows:</p><div class="informalexample"><pre class="programlisting">
<span class="strong"><strong>$ python heal_exception_example.py </strong></span>
<span class="strong"><strong>Creating a Knight..</strong></span>
<span class="strong"><strong>Health: Sir Bar: 10</strong></span>
<span class="strong"><strong>health_meter &gt; max_hp!</strong></span>
<span class="strong"><strong>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</strong></span>
<span class="strong"><strong>ERROR: Health Meter Problem</strong></span>
<span class="strong"><strong>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</strong></span>

<span class="strong"><strong>Health: Sir Bar: 110</strong></span>
</pre></div><p>Likewise, you can create<a id="id143" class="indexterm"/> other subclasses to deal with specific issues.</p></div></div>
<div class="section" title="Exercise"><div class="titlepage"><div><div><h1 class="title"><a id="ch02lvl1sec21"/>Exercise</h1></div></div></div><p>Identify any code that can benefit from exception handling. For example, create a new <code class="literal">HutError</code> exception, and use it to raise errors related to the <code class="literal">Hut</code> class. Here is a cheat sheet:</p><div class="mediaobject"><img src="graphics/B05034_02_27.jpg" alt="Exercise"/></div><p>Instead of using <code class="literal">error_dict</code>, you can also create subclasses, such as:</p><div class="informalexample"><pre class="programlisting">class HutNumberGreaterThanFiveError(HutError): pass
class NegativeHutNumberError(HutError): pass </pre></div></div>
<div class="section" title="Summary"><div class="titlepage"><div><div><h1 class="title"><a id="ch02lvl1sec22"/>Summary</h1></div></div></div><p>This chapter served as an introduction to the basics of exception handling in Python. We saw how the exceptions occur, learned about some common built-in exception classes, and wrote simple code to handle these exceptions using the <code class="literal">try…except</code> clause. By handling exceptions, we fixed some obvious bugs in the <span class="emphasis"><em>Attack of the Orcs</em></span> game.</p><p>The chapter also demonstrated techniques, such as raising and re-raising exceptions, using the <code class="literal">finally</code> clause, and so on. The later part of the chapter focused on implementing custom exception classes. We defined a new exception class and used it for raising custom exceptions for our application.</p><p>With exception handling, the code is in a better shape. However, we still have the majority of the code squished inside a single file (<code class="literal">attackoftheorcs_v1_1.py</code>). In the next chapter, you will learn how to package the application code and release it to a broader audience.</p></div></body></html>